### ISSUE TITLE
Rd files with duplicated alias

### ISSUE THREAD

**Issue by mladenjovanovic** [tidymodels/hardhat#130]
I have run devtools::check() command for the package built by hardhat. And I get the following warning:

"Rd files with duplicated alias" 
<img width="413" alt="Screenshot 2020-04-27 at 23 49 38" src="https://user-images.githubusercontent.com/39139548/80424427-ffde4f80-88e1-11ea-8bb4-a5eb9aa0029d.png">

I suppose that this function generates this issue for the devtools::check()

<img width="734" alt="Screenshot 2020-04-27 at 23 49 50" src="https://user-images.githubusercontent.com/39139548/80424474-17b5d380-88e2-11ea-96a4-0309e4a217ce.png">

Package source code can be found at github.com/mladenjovanovic/dorem

**Comment by DavisVaughan** [comment]
Because you have a function `dorem()` with the same name as the package {dorem}, you get two man files that both try to be what `?dorem` points to. The easiest way to fix it is to limit the package aliases by doing this, and then redocumenting

https://github.com/DavisVaughan/testduplicate/blob/7c4c6ce09b3131d966cda91c6fb6a67fa6e0bbb5/R/testduplicate-package.R#L2

**Comment by mladenjovanovic** [comment]
Thanks a lot Davis! I appreciate the help and really enjoying the hardhat!
