### ISSUE TITLE
Error in out$extras$final(predictors_extras, outcomes_extras): argument "outcomes_extras" is missing, with no default

### ISSUE THREAD

**Issue by mdancho84** [tidymodels/hardhat#200]
Hey Davis, 

I'm getting an error with `modeltime`, `modeltime.ensemble`, and `modeltime.resample` that is with the new `hardhat 1.0.0`.

```
Error in out$extras$final(predictors_extras, outcomes_extras): argument "outcomes_extras" is missing, with no default
```

It looks like `outcome_extras` is required but for some reason is not getting passed and created making the new `hardhat` not backwards compatible. 

I'm working on creating a reproducible example, but I want to create this as a placeholder. 

Currently the solution is to downgrade to `hardhat 0.2.0` via:

``` r
remotes::install_version("hardhat", version = "0.2.0")
```

**Comment by mdancho84** [comment]
I believe this is where the issue is generated. 

![image](https://user-images.githubusercontent.com/13734662/172212803-e6276305-de70-4827-95e6-45b719851f39.png)

**Comment by mdancho84** [comment]
# Solution

Instead of extracting the mold, I am now creating a new mold from the preprocessor and preprocessor template. May not be the most elegant solution, but should fix the issues in `modeltime.ensemble` and `modeltime.resample`. 

## Do this

``` r
preprocessor <- workflows::extract_preprocessor(workflow)
mld          <- hardhat::mold(preprocessor, preprocessor$template)
forged       <- hardhat::forge(new_data, mld$blueprint)
```

## Not this (will error on old models)

``` r
mld          <- object %>% workflows::extract_mold()
forged       <- hardhat::forge(new_data, mld$blueprint)
```

**Comment by DavisVaughan** [comment]
It turns out that this affects all workflows (I think?) that use a recipe. That was not my intention, but I didn't catch this because we don't do any testing on "old" saved hardhat objects against new versions of hardhat.

A Mac specific reprex is:

Run this with hardhat 0.2.0:

```r
# devtools::install_version("hardhat", "0.2.0")
library(tidymodels)

spline_rec <-
  recipe(mpg ~ ., data = mtcars) %>%
  step_ns(disp, deg_free = 2) %>%
  step_ns(wt, deg_free = 2)

lin_mod <-
  linear_reg() %>%
  set_engine("lm")

wf <- workflow(spline_rec, lin_mod)

model_fit <- fit(wf, mtcars)

path <- "~/Desktop/model.rds"

saveRDS(model_fit, file = path)
```

Then install hardhat 1.0.0, and restart R. Then run:

```r
# hardhat 1.0.0
# install.packages("hardhat")
library(tidymodels)

path <- "~/Desktop/model.rds"

model_fit <- readRDS(path)

predict(model_fit, mtcars)
#> Error in out$extras$final(predictors_extras, outcomes_extras) : 
#>   argument "outcomes_extras" is missing, with no default
```

This occurs because hardhat stores function objects in the results of `hardhat::mold()`, which are then called at `predict()` time through `hardhat::forge()`.

So you can get into a state where you are using an old model that was fit with one version of hardhat, but it is incompatible with a new version of hardhat just because I changed some of the internal details.

In #201 I've rewritten a large chunk of the internals to no longer store the function objects in the blueprint. They are looked up on the fly instead - which should ensure that we always get a "current" version of those functions.

I'll need to do one more follow up PR after that, but I'm fairly confident it'll fix this issue.

**Comment by DavisVaughan** [comment]
@mdancho84, I've finished the work that should make the next version of hardhat compatible with workflows that were save using a version of hardhat that was pre-1.0.0. Is there any way you can test this for me? I've done some tests on my end but nothing with modeltime.

I think you'd need to get the dev version of hardhat + the previous version of modeltime before your patches, and then run your original example with those installed

**Comment by mdancho84** [comment]
I can test after the kids go down tonight. I have some old models that I will try with modeltime.

**Comment by mdancho84** [comment]
Hey Davis, 

I ran the following tests:
- Old models + hardhat dev + modeltime 1.2.2 (remolds): Works 
- Old models + hardhat dev + modeltime 1.2.1 (no remolding): Works

I'd say you are good to go. 

-Matt

**Comment by mdancho84** [comment]
I'll probably wait the 30-days but eventually revert the "re-molding" versions of modeltime R packages.

**Comment by DavisVaughan** [comment]
Thanks, just sent it in. FYI the 30 day limit has been reduced to 6-7 days now for sending in a new release
